"""
app/models/order.py

SQLAlchemy models for the order system.

Models
------
Order            — The parent order record.
OrderItem        — Line items belonging to an order.
OrderStatusHistory — Audit log of status changes.

Design Notes
------------
* Price snapshot: all price components at the time of order placement
  are stored in OrderItem. Historical prices never change even if
  metal rates change in the future.
* order_number: auto-generated human-readable identifier (e.g. "JWE-20260924-0001").
* Payment status is tracked separately on the Payment model.
"""

import enum

from app.extensions import db
from app.models.base import TimestampMixin


class OrderStatus(str, enum.Enum):
    """Lifecycle states of an order."""
    PLACED      = "PLACED"
    CONFIRMED   = "CONFIRMED"
    CRAFTING    = "CRAFTING"
    HALLMARKING = "HALLMARKING"
    SHIPPED     = "SHIPPED"
    DELIVERED   = "DELIVERED"
    CANCELLED   = "CANCELLED"
    RETURNED    = "RETURNED"
    REFUNDED    = "REFUNDED"


class PaymentStatus(str, enum.Enum):
    """Payment state of an order."""
    PENDING  = "PENDING"
    PAID     = "PAID"
    FAILED   = "FAILED"
    REFUNDED = "REFUNDED"


class Order(TimestampMixin, db.Model):
    """
    Represents a customer order.

    Table: orders
    """

    __tablename__ = "orders"

    # ── Primary key ───────────────────────────────────────────────────────────
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)

    # ── Human-readable order number ───────────────────────────────────────────
    # Format: JWE-YYYYMMDD-NNNN (generated by OrderService)
    order_number = db.Column(
        db.String(30),
        nullable=False,
        unique=True,
        index=True,
    )

    # ── Customer ──────────────────────────────────────────────────────────────
    user_id = db.Column(
        db.Integer,
        db.ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )

    # ── Delivery address snapshot ──────────────────────────────────────────────
    # Store the full address as a snapshot — not a FK — so that if the user
    # later updates their address profile, the order address is unaffected.
    shipping_name    = db.Column(db.String(120), nullable=True)
    shipping_phone   = db.Column(db.String(20),  nullable=True)
    shipping_line1   = db.Column(db.String(200), nullable=True)
    shipping_line2   = db.Column(db.String(200), nullable=True)
    shipping_city    = db.Column(db.String(100), nullable=True)
    shipping_state   = db.Column(db.String(100), nullable=True)
    shipping_pincode = db.Column(db.String(10),  nullable=True)
    shipping_country = db.Column(db.String(100), nullable=True, default="India")

    # ── Price breakdown ───────────────────────────────────────────────────────
    # All values in INR, stored as Numeric for accuracy.
    subtotal        = db.Column(db.Numeric(12, 2), nullable=False, default=0)
    making_charges  = db.Column(db.Numeric(12, 2), nullable=False, default=0)
    stone_charges   = db.Column(db.Numeric(12, 2), nullable=False, default=0)
    gst_amount      = db.Column(db.Numeric(12, 2), nullable=False, default=0)
    discount_amount = db.Column(db.Numeric(12, 2), nullable=False, default=0)
    total_amount    = db.Column(db.Numeric(12, 2), nullable=False, default=0)

    # ── Coupon ────────────────────────────────────────────────────────────────
    coupon_code     = db.Column(db.String(50), nullable=True)

    # ── Status ────────────────────────────────────────────────────────────────
    order_status    = db.Column(
        db.String(20),
        nullable=False,
        default=OrderStatus.PLACED,
        index=True,
    )
    payment_status  = db.Column(
        db.String(20),
        nullable=False,
        default=PaymentStatus.PENDING,
        index=True,
    )
    payment_method = db.Column(db.String(50), nullable=True, default="UPI")

    # ── Notes ─────────────────────────────────────────────────────────────────
    notes = db.Column(db.Text, nullable=True)

    # ── Relationships ─────────────────────────────────────────────────────────
    user = db.relationship("User", backref=db.backref("orders", lazy="dynamic"))

    items = db.relationship(
        "OrderItem",
        back_populates="order",
        cascade="all, delete-orphan",
        lazy="select",
    )

    status_history = db.relationship(
        "OrderStatusHistory",
        back_populates="order",
        cascade="all, delete-orphan",
        lazy="select",
        order_by="OrderStatusHistory.created_at.asc()",
    )

    def __repr__(self) -> str:
        return f"<Order id={self.id} number={self.order_number!r} status={self.order_status}>"


class OrderItem(TimestampMixin, db.Model):
    """
    Represents a single product line item in an order.

    All pricing fields are SNAPSHOTS captured at order placement.

    Table: order_items
    """

    __tablename__ = "order_items"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)

    order_id = db.Column(
        db.Integer,
        db.ForeignKey("orders.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    product_id = db.Column(
        db.Integer,
        db.ForeignKey("products.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )

    # ── Product snapshot ──────────────────────────────────────────────────────
    product_name  = db.Column(db.String(200), nullable=False)
    product_sku   = db.Column(db.String(100), nullable=False)
    metal_type    = db.Column(db.String(50),  nullable=True)
    purity        = db.Column(db.String(20),  nullable=True)
    net_weight    = db.Column(db.Numeric(10, 2), nullable=True)
    gross_weight  = db.Column(db.Numeric(10, 2), nullable=True)

    quantity = db.Column(db.Integer, nullable=False, default=1)

    # ── Price snapshot ────────────────────────────────────────────────────────
    rate_per_gram    = db.Column(db.Numeric(12, 2), nullable=True)  # rate at time of order
    base_metal_value = db.Column(db.Numeric(12, 2), nullable=True)
    making_charge    = db.Column(db.Numeric(12, 2), nullable=False, default=0)
    stone_charge     = db.Column(db.Numeric(12, 2), nullable=False, default=0)
    gst_percentage   = db.Column(db.Numeric(5, 2),  nullable=False, default=0)
    gst_amount       = db.Column(db.Numeric(12, 2), nullable=False, default=0)
    item_total       = db.Column(db.Numeric(12, 2), nullable=False, default=0)

    # ── Relationships ─────────────────────────────────────────────────────────
    order   = db.relationship("Order", back_populates="items")
    product = db.relationship("Product", backref=db.backref("order_items", lazy="dynamic"))

    def __repr__(self) -> str:
        return f"<OrderItem id={self.id} order_id={self.order_id} sku={self.product_sku!r}>"


class OrderStatusHistory(TimestampMixin, db.Model):
    """
    Audit log — records every status change made to an order.

    Table: order_status_history
    """

    __tablename__ = "order_status_history"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)

    order_id = db.Column(
        db.Integer,
        db.ForeignKey("orders.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    old_status = db.Column(db.String(20), nullable=True)   # None for first entry
    new_status = db.Column(db.String(20), nullable=False)
    changed_by = db.Column(db.Integer, db.ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    notes      = db.Column(db.Text, nullable=True)

    order = db.relationship("Order", back_populates="status_history")

    def __repr__(self) -> str:
        return (
            f"<OrderStatusHistory id={self.id} order_id={self.order_id} "
            f"{self.old_status} → {self.new_status}>"
        )
