"""
app/models/token_blacklist.py

SQLAlchemy model for the `token_blacklist` table.

Purpose
-------
When a user logs out, the JWT tokens they hold are still cryptographically
valid until they expire.  To prevent those tokens from being used after
logout, we store their unique JWT ID (`jti`) in this table.

The `token_in_blocklist_loader` callback registered in app/__init__.py
checks this table on every protected request.  If the token's `jti` is
found here, the request is rejected with 401.

Cleanup
-------
Tokens that have already expired are harmless (they'd be rejected by
Flask-JWT-Extended before our blocklist check), but they accumulate.
The `cleanup_expired_tokens()` method in TokenBlacklistService handles
removal of stale rows.  Run it periodically via a cron job or scheduled
task in production.

Security notes
--------------
* We store the `jti` (JWT ID claim), NOT the raw token string.  The jti
  is a random UUID generated by Flask-JWT-Extended — it is unique and
  unforgeable.
* Both access tokens and refresh tokens can be revoked.  On logout, at
  minimum the access token is revoked.  If the client also sends its
  refresh token in the request body, that is revoked too.
"""

from datetime import datetime, timezone

from app.extensions import db
from app.models.base import TimestampMixin


class TokenBlacklist(TimestampMixin, db.Model):
    """
    Stores JWT token identifiers (jti) that have been explicitly revoked.

    Table: token_blacklist
    """

    __tablename__ = "token_blacklist"

    # ── Primary key ───────────────────────────────────────────────────────────
    id = db.Column(
        db.Integer,
        primary_key=True,
        autoincrement=True,
    )

    # ── JWT ID — the unique claim that identifies a specific token ─────────────
    # jti is a UUID string generated by Flask-JWT-Extended (e.g.
    # "a3f1c2d4-...").  It is globally unique per token.
    jti = db.Column(
        db.String(36),   # UUID is 36 characters with hyphens
        nullable=False,
        unique=True,
        index=True,      # critical: every protected request queries this column
    )

    # ── Token type ────────────────────────────────────────────────────────────
    # "access" or "refresh" — stored for auditing and selective revocation.
    token_type = db.Column(
        db.String(10),
        nullable=False,
    )

    # ── When the token naturally expires ─────────────────────────────────────
    # Used by cleanup_expired_tokens() to prune stale rows.
    # After this time the token would be rejected by Flask-JWT-Extended anyway,
    # so keeping it in the blacklist beyond this point is wasteful.
    expires_at = db.Column(
        db.DateTime(timezone=True),
        nullable=False,
        index=True,      # cleanup query filters on this column
    )

    # ── Who revoked it ────────────────────────────────────────────────────────
    # Nullable FK to users.id — SET NULL if the user is deleted so that the
    # audit row is preserved even after account deletion.
    user_id = db.Column(
        db.Integer,
        db.ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # ── Convenience property ──────────────────────────────────────────────────

    @property
    def is_expired(self) -> bool:
        """True if the token's natural expiry time has already passed."""
        now = datetime.now(timezone.utc)
        expiry = self.expires_at
        if expiry.tzinfo is None:
            expiry = expiry.replace(tzinfo=timezone.utc)
        return now > expiry

    def __repr__(self) -> str:
        return (
            f"<TokenBlacklist id={self.id} jti={self.jti!r} "
            f"type={self.token_type!r} user_id={self.user_id}>"
        )
