"""add payment_method to order

Revision ID: 691bdecc6062
Revises: 7ff6f5baf0b8
Create Date: 2026-09-26 13:32:43.936941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691bdecc6062'
down_revision = '7ff6f5baf0b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
